---
title: "Mini-Project 2"
author: "Liu Sifan & Ziheng Ru & Runxin Wang"
date: "October 31, 2017"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
```

```{r}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
house_elections <-
  rename(house_elections, cand_name = candidate_name )
```

```{r}
Fl_winner <- house_elections %>%
  filter(state == "FL") %>%
  filter(ge_winner == "W") %>%
  filter(party == "R"| party == "D")
List_winner1 <- Fl_winner %>%
  select("cand_name","fec_id") %>%
  rename("cand_id"="fec_id")
List_winner1
```

```{r}
Fl_general_candidates <- house_elections %>%
  filter(state == "FL") %>%
  filter(ge_winner == "W"| general_votes > 0 & ge_winner == "N") %>%
  filter(party == "R"| party == "D") %>%
  select("cand_name","fec_id","district","general_votes","ge_winner") %>%
  rename("cand_id"="fec_id")
Fl_general_candidates
```



```{r}
FL_win <- Fl_winner %>%
  summarise(N = n(),
            r = sum(party == "R")) %>%
  mutate(r_percentage = r/N)
FL_win
```

```{r}
committees_contribution <- committees %>%
  left_join(contributions, by = "cmte_id")
```

```{r}
committees_contribution <- committees_contribution %>%
  rename( cand_id = cand_id.y)
```

```{r}
committees_contribution_2 <- committees_contribution %>%
  right_join(candidates, by = "cand_id")
```

```{r}
FL_dataset <- committees_contribution_2 %>%
  right_join(Fl_general_candidates, by="cand_id") %>%
  rename(cand_name= cand_name.y) %>%
    filter(cand_office=="H" ) %>%
  select("cand_name","district","cmte_dsgn","ge_winner","cand_id","cand_party_affiliation","cmte_party_affiliation","cmte_name","cmte_id","cmte_state","cmte_type","transaction_type","transaction_amt","memo_text")
FL_dataset
```
```{r}
FL_dataset_2 <- FL_dataset %>%
  filter(cmte_party_affiliation=="DEM" | cmte_party_affiliation=="REP") %>%
  group_by(district,cand_name,cand_party_affiliation) %>%
  summarise(sum_for=sum(ifelse( transaction_type=="24C"| transaction_type=="24E" | transaction_type=="24F"| transaction_type=="24H" | transaction_type=="24K" | transaction_type=="24P" | transaction_type=="24R" | transaction_type=="24Z",transaction_amt, 0)), sum_against=sum(ifelse( transaction_type=="24A"| transaction_type=="24N",transaction_amt, 0))) %>%
mutate(sum_for-sum_against)

```

```{r}
FL_dataset_3 <- FL_dataset_2 %>%
group_by(district_name = district + cand_name)
```

FL_dataset_3[1:2,"sum_against"] <- FL_dataset_3[2:1,"sum_against"]

```

  mutate(for= transaction_type=="24C"| transaction_type=="24E" | transaction_type=="24F"| transaction_type=="24H" | transaction_type=="24K" | transaction_type=="24P" | transaction_type=="24R" | transaction_type=="24Z") %>%



```